// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFO5KR6g8lajnv81iFAqPDEnGZ74C1iuI',
    appId: '1:576829421900:web:b60ed4e7c9afa904d2b7e9',
    messagingSenderId: '576829421900',
    projectId: 'mr-beast-burger',
    authDomain: 'mr-beast-burger.firebaseapp.com',
    databaseURL: 'https://mr-beast-burger-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mr-beast-burger.appspot.com',
    measurementId: 'G-F55HSJEZN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkrJny-Mtzf-sYqeCSbX-HbVY-RCG3Y68',
    appId: '1:576829421900:android:9cb40596f8691d00d2b7e9',
    messagingSenderId: '576829421900',
    projectId: 'mr-beast-burger',
    databaseURL: 'https://mr-beast-burger-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mr-beast-burger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB62eag4NoLJPt_UpIcja734kZni_t0blg',
    appId: '1:576829421900:ios:6d5a4f73e80f1684d2b7e9',
    messagingSenderId: '576829421900',
    projectId: 'mr-beast-burger',
    databaseURL: 'https://mr-beast-burger-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mr-beast-burger.appspot.com',
    iosBundleId: 'com.example.flutterWebTest',
  );
}
